name: coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install
      run: sudo apt install -y lcov gcovr
    - name: build with coverage
      run: gcc --coverage main.c
    - name: run with coverage
      run: ./a.out
    - name: gcovr
      run: gcovr --xml --output=coverage.xml  .

    #- name: Generate a code coverage report
    #  uses: threeal/gcovr-action@v1.0.0
    - name: show gcovr
      id: gcovr-text
      run: gcovr .
    - name: Create comment
      if: ${{ steps.gcovr-text.outputs.enabled }}
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: | 
          ```
          ${{ steps.get-comment-body.outputs.body }}
          ```
