name: coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  checks: write
  pull-requests: write 

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install
      run: sudo apt install -y lcov gcovr
    - name: build with coverage
      run: gcc --coverage main.c
    - name: run with coverage
      run: ./a.out
    - name: gcovr
      run: gcovr --xml --output=coverage.xml  .

    #- name: Generate a code coverage report
    #  uses: threeal/gcovr-action@v1.0.0
    - name: show gcovr
      id: gcovr-text
      run: |
        echo '```'  >  gcov.txt
        gcovr .     >> gcov.txt
        echo '```'  >> gcov.txt
    - name: Create comment
      if: github.event_name == 'pull_request'
      uses: peter-evans/create-or-update-comment@v4
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body-path: gcov.txt
